" Enable syntax highlighting
syntax on

" Use terminal colors
syntax on
set termguicolors
set background=dark
colorscheme tokyonight

" colorscheme default

" Use 4 spaces for indentation
set tabstop=4       " Number of visual spaces per TAB
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent
set expandtab       " Use spaces instead of tabs

" Enable smart indenting
set smartindent
set autoindent
set viminfo=
