" Use terminal colors
syntax on
set termguicolors
set background=dark
colorscheme tokyonight
highlight Normal ctermbg=none guibg=NONE

" Use 4 spaces for indentation
set tabstop=4       " Number of visual spaces per TAB
set shiftwidth=4    " Number of spaces to use for each step of (auto)indent
set expandtab       " Use spaces instead of tabs
set relativenumber

" Enable smart indenting
set smartindent
set autoindent
set viminfo=
